### ISSUE TITLE
Issues building .dmg file using make_osx

### ISSUE THREAD

**Issue by Abstract45** [qtumproject/qtum-electrum#118]
Was trying to test something out and tried to build a mac os dmg file with the make_osx executable but I run into an issue with the following errors. Wondering if I am installing anything incorrectly. I am able to build the app through the `./run_electrum` executable and it runs fine but just not build a`.dmg` file 

```    ERROR: Command errored out with exit status 1:
     command: /Users/Abstract/qtum-electrum/contrib/osx/build-venv/bin/python3 /Users/Abstract/qtum-electrum/contrib/osx/build-venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/ww/tnx6n7ns6892wkx_hk8srm4w0000gn/T/tmpr57ln9kx
         cwd: /private/var/folders/ww/tnx6n7ns6892wkx_hk8srm4w0000gn/T/pip-install-km8jdgag/pyinstaller
    Complete output (42 lines):
    Traceback (most recent call last):
      File "/Users/Abstract/qtum-electrum/contrib/osx/build-venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/Users/Abstract/qtum-electrum/contrib/osx/build-venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/Users/Abstract/qtum-electrum/contrib/osx/build-venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/private/var/folders/ww/tnx6n7ns6892wkx_hk8srm4w0000gn/T/pip-build-env-j6cd07lk/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 188, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/private/var/folders/ww/tnx6n7ns6892wkx_hk8srm4w0000gn/T/pip-build-env-j6cd07lk/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 282, in run_setup
        self).run_setup(setup_script=setup_script)
      File "/private/var/folders/ww/tnx6n7ns6892wkx_hk8srm4w0000gn/T/pip-build-env-j6cd07lk/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 174, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 78, in <module>
        'build': MyBuild,
      File "/private/var/folders/ww/tnx6n7ns6892wkx_hk8srm4w0000gn/T/pip-build-env-j6cd07lk/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 79, in setup
        return distutils.core.setup(**attrs)
      File "/private/var/folders/ww/tnx6n7ns6892wkx_hk8srm4w0000gn/T/pip-build-env-j6cd07lk/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 122, in setup
        dist.parse_config_files()
      File "/private/var/folders/ww/tnx6n7ns6892wkx_hk8srm4w0000gn/T/pip-build-env-j6cd07lk/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 833, in parse_config_files
        self, self.command_options, ignore_option_errors=ignore_option_errors
      File "/private/var/folders/ww/tnx6n7ns6892wkx_hk8srm4w0000gn/T/pip-build-env-j6cd07lk/overlay/lib/python3.7/site-packages/setuptools/config/setupcfg.py", line 167, in parse_configuration
        meta.parse()
      File "/private/var/folders/ww/tnx6n7ns6892wkx_hk8srm4w0000gn/T/pip-build-env-j6cd07lk/overlay/lib/python3.7/site-packages/setuptools/config/setupcfg.py", line 446, in parse
        section_parser_method(section_options)
      File "/private/var/folders/ww/tnx6n7ns6892wkx_hk8srm4w0000gn/T/pip-build-env-j6cd07lk/overlay/lib/python3.7/site-packages/setuptools/config/setupcfg.py", line 417, in parse_section
        self[name] = value
      File "/private/var/folders/ww/tnx6n7ns6892wkx_hk8srm4w0000gn/T/pip-build-env-j6cd07lk/overlay/lib/python3.7/site-packages/setuptools/config/setupcfg.py", line 238, in __setitem__
        value = parser(value)
      File "/private/var/folders/ww/tnx6n7ns6892wkx_hk8srm4w0000gn/T/pip-build-env-j6cd07lk/overlay/lib/python3.7/site-packages/setuptools/config/setupcfg.py", line 552, in _parse_version
        return expand.version(self._parse_attr(value, self.package_dir, self.root_dir))
      File "/private/var/folders/ww/tnx6n7ns6892wkx_hk8srm4w0000gn/T/pip-build-env-j6cd07lk/overlay/lib/python3.7/site-packages/setuptools/config/setupcfg.py", line 372, in _parse_attr
        return expand.read_attr(attr_desc, package_dir, root_dir)
      File "/private/var/folders/ww/tnx6n7ns6892wkx_hk8srm4w0000gn/T/pip-build-env-j6cd07lk/overlay/lib/python3.7/site-packages/setuptools/config/expand.py", line 194, in read_attr
        module = _load_spec(spec, module_name)
      File "/private/var/folders/ww/tnx6n7ns6892wkx_hk8srm4w0000gn/T/pip-build-env-j6cd07lk/overlay/lib/python3.7/site-packages/setuptools/config/expand.py", line 214, in _load_spec
        spec.loader.exec_module(module)  # type: ignore
      File "<frozen importlib._bootstrap_external>", line 728, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/private/var/folders/ww/tnx6n7ns6892wkx_hk8srm4w0000gn/T/pip-install-km8jdgag/pyinstaller/PyInstaller.py", line 16, in <module>
        from PyInstaller.__main__ import run
    ModuleNotFoundError: No module named 'PyInstaller.__main__'; 'PyInstaller' is not a package
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/Abstract/qtum-electrum/contrib/osx/build-venv/bin/python3 /Users/Abstract/qtum-electrum/contrib/osx/build-venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/ww/tnx6n7ns6892wkx_hk8srm4w0000gn/T/tmpr57ln9kx Check the logs for full command output.```

**Comment by icodeface** [comment]
fixex in https://github.com/qtumproject/qtum-electrum/commit/96dc267d5d1cb9132f29bd847833c5d0c39a6191
