### ISSUE TITLE
ModuleNotFoundError: No module named 'Cryptodome'

### ISSUE THREAD

**Issue by Tazeg** [qtumproject/qtum-electrum#49]
On Ubuntu 17.10
```
./qtum-electrum

Traceback (most recent call last):
  File "./qtum-electrum", line 54, in check_imports
    import eth_utils
  File "/home/jeff/.local/lib/python3.6/site-packages/eth_utils/__init__.py", line 5, in <module>
    from .abi import (  # noqa: F401
  File "/home/jeff/.local/lib/python3.6/site-packages/eth_utils/abi.py", line 1, in <module>
    from .crypto import keccak
  File "/home/jeff/.local/lib/python3.6/site-packages/eth_utils/crypto.py", line 1, in <module>
    from eth_hash.auto import keccak as keccak_256
  File "/home/jeff/.local/lib/python3.6/site-packages/eth_hash/auto.py", line 4, in <module>
    from eth_hash.utils import (
  File "/home/jeff/.local/lib/python3.6/site-packages/eth_hash/utils.py", line 3, in <module>
    import eth_hash.backends.pycryptodomex
  File "/home/jeff/.local/lib/python3.6/site-packages/eth_hash/backends/pycryptodomex.py", line 1, in <module>
    from Cryptodome.Hash import (
ModuleNotFoundError: No module named 'Cryptodome'
Error: No module named 'Cryptodome'. Try 'sudo pip install <module-name>'
```
Then
`sudo pip install Cryptodome` or `sudo pip3 install Cryptodome` says `No matching distribution found for Cryptodome`

**Comment by icodeface** [comment]
please follow the instructions https://github.com/qtumproject/qtum-electrum/blob/master/README.md#development-version
