### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-45xh527h/publicsuffix/

### ISSUE THREAD

**Issue by Dmitry-SigmaSW** [qtumproject/qtum-electrum#83]
Hello everyone. I'm encountering an issue during dependencies installation. I'm using Ubuntu 18.04 as OS and Docker as the platform. The output below:

` Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-45xh527h/publicsuffix/setup.py", line 19, in <module>
        long_description=get_long_description(),
      File "/tmp/pip-build-45xh527h/publicsuffix/setup.py", line 13, in get_long_description
        read_doc("LICENSE")
      File "/tmp/pip-build-45xh527h/publicsuffix/setup.py", line 7, in read_doc
        return open(os.path.join(os.path.dirname(__file__), name)).read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 23: ordinal not in range(128)`

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-45xh527h/publicsuffix/

**Comment by icodeface** [comment]
seems to be a [publicsuffix](https://pypi.org/project/publicsuffix/) installation issue

**Comment by icodeface** [comment]
see https://stackoverflow.com/questions/25036897/pip-install-unicodedecodeerror
