### ISSUE TITLE
Crash on macOS

### ISSUE THREAD

**Issue by markshep** [qtumproject/qtum-electrum#91]
When I run "Qtum Electrum" it pops up a dialog box asking for the password.  After entering it the app exits immediately.  Running it from the command shows the following output:

```
[ecc] warning: libsecp256k1 library not available, falling back to python-ecdsa
Traceback (most recent call last):
  File "qtum_electrum/daemon.py", line 328, in init_gui
  File "qtum_electrum/gui/qt/__init__.py", line 296, in main
  File "qtum_electrum/gui/qt/__init__.py", line 187, in wrapper
  File "qtum_electrum/gui/qt/__init__.py", line 208, in start_new_window
  File "qtum_electrum/gui/qt/__init__.py", line 245, in _start_wizard_to_select_or_create_wallet
  File "qtum_electrum/gui/qt/installwizard.py", line 325, in run_upgrades
  File "qtum_electrum/base_wizard.py", line 144, in upgrade_storage
TypeError: waiting_dialog() got an unexpected keyword argument 'on_finished'
```

I'm running on macOS 10.14.3.

**Comment by L1Cafe** [comment]
I am experiencing a similar issue.

Did you use Qtum Electrum before? Do you have the wallet already set up?
